global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'varshitha.k@exclcloud.com'
  smtp_auth_username: 'varshitha.k@exclcloud.com'
  smtp_auth_password: 'wirtdmfxyqyfczmf'
  smtp_require_tls: true

route:
  receiver: 'email-alerts'
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 4h

receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'varshitha.k@exclcloud.com'
    send_resolved: true
